# Generated by Django 3.0.8 on 2020-08-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tasklist_manage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manage',
        ),
    ]
